/* ============================================================
   REFRESH S.A. — Planta de Detergente en Polvo · Panamá
   Asignación #6 — Distribución de Planta
   Modelo de datos maestro compartido (PLANT_DATA)
   Coordenadas en metros sobre terreno 100 × 100 m (norte arriba,
   x: oeste→este, y: norte→sur).
   ============================================================ */

const PLANT_DATA = {
  proyecto: {
    titulo: 'REFRESH S.A. — Planta de Detergente en Polvo · Panamá',
    asignacion: 'Asignación #6 — Distribución de Planta',
    escala: '1:250 · Cotas en metros',
    fecha: 'Junio 2026',
    terreno: { w: 100, h: 100, area: 10000 },
    vialPerimetral: 7,
    radioGiro: 15,
  },

  // ---------------- EDIFICIOS Y ÁREAS ----------------
  edificios: {
    naveA: {
      id: 'naveA', tipo: 'edificio', nombre: 'Nave A — Área de Proceso',
      pos: { x: 8, y: 34, w: 40, h: 20 }, altura: 22,
      dims: '40 × 20 m · Altura libre 22 m en zona de torre',
      color: '#dce8f5',
      ficha: {
        funcion: 'Alberga la línea de proceso: mezclado (TK-101/TK-102), bombeo de alta presión, Torre de Secado GEA NIRO®, enfriador/tamizador, post-adición y tolvas buffer.',
        detalles: ['Altura libre 22 m en zona de torre', 'Portones doble hoja 2.40 m con sello cortafuego hermético', 'Pasarela de interconexión cerrada de 3.00 m hacia Nave B', 'Clasificación de áreas con zonas ATEX por polvo combustible'],
        alimentacion: 'MCC-A 1600 A, 480 V, 3Ø, 60 Hz (Centro de Carga 1)',
      },
    },
    naveB: {
      id: 'naveB', tipo: 'edificio', nombre: 'Nave B — Área de Envasado',
      pos: { x: 10, y: 62, w: 30, h: 18 }, altura: 10,
      dims: '30 × 18 m',
      color: '#dcf0e2',
      ficha: {
        funcion: 'Línea ÚNICA de envasado con bifurcación final (distribuidor de flujo): Módulo A (VFFS hogar) o Módulo B (ensacadora industrial). Solo un módulo opera a la vez. Incluye checkweigher, detector de metales, bandas BC-101/BC-102 y paletizador robot.',
        detalles: ['Conectada a Nave A por pasillo técnico cerrado de 3.00 m', 'Almacenamiento temporal de pallets 1.20 × 1.00 m', 'Salida a 4 bahías de despacho al sur'],
        alimentacion: 'MCC-B 600 A nominal / 800 A frame, 480 V, 3Ø, 60 Hz (Centro de Carga 2)',
      },
    },
    edifC: {
      id: 'edifC', tipo: 'edificio', nombre: 'Edificio C — Servicios Industriales',
      pos: { x: 52, y: 34, w: 12, h: 24 }, altura: 8,
      dims: '24 × 12 m',
      color: '#f5e8dc',
      ficha: {
        funcion: 'Servicios industriales de la planta: S-1 sala de calderas (vapor 8 barg, ATEX), S-2 sala de compresores + planta de agua desmineralizada RO+EDI (ATEX), S-3 sala eléctrica / generador / UPS (ATEX).',
        detalles: ['Rack de tuberías aéreo hacia Nave A (vapor, aire 7 barg, agua DI)', 'Subestación 1,500 kVA 13.8 kV Δ – 480Y/277 V', 'Generador AES gas natural 1,500 kW + ATS 1600 A', 'UPS industrial 100 kVA para PLC/DCS'],
        alimentacion: 'Acometida Naturgy 13.8 kV, 3Ø, 60 Hz',
      },
    },
    edifD: {
      id: 'edifD', tipo: 'edificio', nombre: 'Edificio D — Operativo y Planta',
      pos: { x: 43, y: 64, w: 25, h: 12 }, altura: 6,
      dims: '25 × 12 m',
      color: '#ece5f5',
      ficha: {
        funcion: 'Áreas operativas de soporte: Laboratorio de Control de Calidad (QC), comedor, baños y lockers (hombres y mujeres), taller de mantenimiento mecánico y eléctrico.',
        detalles: ['Panel PD-D 480Y/277 V, 3Ø, 4W, 400 A', 'Tableros TLD iluminación 277 V y TTD tomacorrientes 120/208 V'],
        alimentacion: 'Panel PD-D 400 A — 480Y/277 V desde Edificio C',
      },
    },
    edifE: {
      id: 'edifE', tipo: 'edificio', nombre: 'Edificio E — Corporativo',
      pos: { x: 9, y: 9, w: 20, h: 10 }, altura: 5,
      dims: '20 × 10 m',
      color: '#f5f0dc',
      ficha: {
        funcion: 'Recepción, oficinas corporativas y sala de juntas.',
        detalles: ['Panel PD-E 480Y/277 V, 3Ø, 4W, 400 A', 'Acceso desde estacionamiento de visitas'],
        alimentacion: 'Panel PD-E 400 A — 480Y/277 V desde Edificio C',
      },
    },
    patioSilos: {
      id: 'patioSilos', tipo: 'edificio', nombre: 'Patio de Silos Exterior (techado)',
      pos: { x: 46, y: 21, w: 15, h: 10 }, altura: 14,
      dims: '15 × 10 m · 4 silos Ø2.50 m',
      color: '#e3e3e3',
      ficha: {
        funcion: 'Recepción y almacenamiento de materias primas a granel. 4 silos Ø2.50 m con elevadores de cangilones y transporte neumático hacia dosificación en Nave A.',
        detalles: ['Etapa ① del flujo de proceso — Recepción de MP', 'Acceso de camiones de materia prima por el norte'],
        alimentacion: '480 V, 3Ø — elevadores de cangilones y sopladores',
      },
    },
    estacionamiento: {
      id: 'estacionamiento', tipo: 'edificio', nombre: 'Estacionamientos (30 puestos)',
      pos: { x: 31, y: 9, w: 30, h: 10 }, altura: 0,
      dims: '30 puestos · incluye accesibles SENADIS',
      color: '#e9edf0',
      ficha: {
        funcion: 'Estacionamiento para personal y visitas, 30 puestos incluyendo puestos accesibles conforme SENADIS (Panamá).',
        detalles: ['Demarcación accesible junto a Edificio E', 'Semáforos acústicos y luminosos en cruces peatonales'],
        alimentacion: 'Iluminación 277 V desde TLD',
      },
    },
    bahias: {
      id: 'bahias', tipo: 'edificio', nombre: 'Bahías de Despacho (4)',
      pos: { x: 12, y: 84, w: 28, h: 7 }, altura: 6,
      dims: '4 bahías · salida sur',
      color: '#dde6dd',
      ficha: {
        funcion: 'Despacho de producto terminado (pallets) hacia camiones. Etapa ⑩ final del flujo.',
        detalles: ['Salida de producto terminado al sur del terreno', 'Andenes con sellos y rampas niveladoras'],
        alimentacion: '480 V / 120 V — rampas niveladoras y puertas',
      },
    },
    expansion: {
      id: 'expansion', tipo: 'edificio', nombre: 'Área de Expansión Futura',
      pos: { x: 70, y: 9, w: 22, h: 82 }, altura: 0,
      dims: '3,000 m² (30 % del terreno) · lado este',
      color: '#f2f5ec',
      ficha: {
        funcion: 'Reserva de terreno (3,000 m²) en el lado este para crecimiento futuro de la planta.',
        detalles: ['Permite duplicar capacidad de envasado o añadir segunda torre'],
        alimentacion: '—',
      },
    },
  },

  // ---------------- EQUIPOS PRINCIPALES ----------------
  equipos: {
    silos: {
      id: 'silos', tipo: 'equipo', nombre: 'Silos de Materia Prima (4)', etapa: 1,
      marca: '4 silos Ø2.50 m + elevadores de cangilones',
      pos: { x: 47.5, y: 24.5, w: 13, h: 4 }, alturaEq: 12, edificio: 'patioSilos',
      dims: 'Ø2.50 m c/u, altura ~12 m', peso: '8–10 t c/u (llenos: 40 t)',
      alimentacion: '480 V, 3Ø, 60 Hz — elevadores y sopladores ~15 HP, desde MCC-A',
      consumos: 'Aire comprimido para fluidización (7 barg)',
      materiales: 'Acero al carbono con recubrimiento epóxico interior · zona ATEX 22',
      velocidad: 'Descarga regulada por dosificación gravimétrica',
      conexiones: { aguasArriba: 'Camiones cisterna / tolva de recepción (norte)', aguasAbajo: 'Dosificación y pesado (transporte neumático) → TK-101/TK-102' },
      faseProducto: 'Sólido / líquido a granel',
    },
    tk101: {
      id: 'tk101', tipo: 'equipo', nombre: 'Tanque de Mezcla TK-101 (Mezcla 1)', etapa: 3,
      marca: 'Tanque SS 316L 10,000 L + agitador M-101',
      pos: { x: 10, y: 36.5, w: 3, h: 3 }, alturaEq: 5, edificio: 'naveA',
      dims: 'Ø3.0 m × 4.5 m, 10,000 L', peso: '4 t vacío / 14 t lleno',
      alimentacion: '480 V, 3Ø, 60 Hz — Mezclador M-101: 75 HP desde MCC-A (VFD-101)',
      consumos: 'Vapor 8 barg (calefacción) · agua DI (S-3) · CIP',
      materiales: 'AISI 316L pulido sanitario · instrumentación LT-101',
      velocidad: 'Lote de slurry 35–45 % sólidos a 65–75 °C',
      conexiones: { aguasArriba: 'Dosificación de MP (silos, etapa ②)', aguasAbajo: 'Bombas P-101/P-102 → filtro Y F-401 → torre' },
      faseProducto: '🔵 SLURRY LÍQUIDO 35–45 % sólidos, 65–75 °C',
    },
    tk102: {
      id: 'tk102', tipo: 'equipo', nombre: 'Tanque de Mezcla TK-102 (Mezcla 2)', etapa: 3,
      marca: 'Tanque SS 316L 10,000 L + agitador',
      pos: { x: 10, y: 41.5, w: 3, h: 3 }, alturaEq: 5, edificio: 'naveA',
      dims: 'Ø3.0 m × 4.5 m, 10,000 L', peso: '4 t vacío / 14 t lleno',
      alimentacion: '480 V, 3Ø, 60 Hz — agitador 75 HP desde MCC-A',
      consumos: 'Vapor 8 barg · agua DI · CIP',
      materiales: 'AISI 316L · instrumentación LT-102',
      velocidad: 'Lote alterno: mientras TK-101 alimenta, TK-102 prepara',
      conexiones: { aguasArriba: 'Dosificación de MP (silos, etapa ②)', aguasAbajo: 'Bombas P-101/P-102 → torre' },
      faseProducto: '🔵 Slurry líquido 65–75 °C',
    },
    p101: {
      id: 'p101', tipo: 'equipo', nombre: 'Bomba de Alta Presión P-101 (principal)', etapa: 4,
      marca: 'Bomba de pistones alta presión 100–250 bar',
      pos: { x: 15, y: 37.5, w: 2, h: 1.2 }, alturaEq: 1.5, edificio: 'naveA',
      dims: '2.0 × 1.2 m', peso: '1.5 t',
      alimentacion: '480 V, 3Ø, 60 Hz — 50 HP desde MCC-A (VFD-102)',
      consumos: 'Agua de sello',
      materiales: 'Internos AISI 316L',
      velocidad: 'Hasta 2,000 kg/h de slurry a 100–250 bar',
      conexiones: { aguasArriba: 'TK-101 / TK-102', aguasAbajo: 'Filtro Y F-401 → línea alta presión (PT-401, FT-402, PCV-401) → boquilla atomizadora' },
      faseProducto: '🔵 Líquido presurizado 100–250 bar',
    },
    p102: {
      id: 'p102', tipo: 'equipo', nombre: 'Bomba de Alta Presión P-102 (reserva)', etapa: 4,
      marca: 'Bomba de pistones alta presión 100–250 bar',
      pos: { x: 15, y: 40.5, w: 2, h: 1.2 }, alturaEq: 1.5, edificio: 'naveA',
      dims: '2.0 × 1.2 m', peso: '1.5 t',
      alimentacion: '480 V, 3Ø, 60 Hz — 50 HP desde MCC-A',
      consumos: 'Agua de sello',
      materiales: 'Internos AISI 316L',
      velocidad: 'Reserva instalada (redundancia N+1)',
      conexiones: { aguasArriba: 'TK-101 / TK-102', aguasAbajo: 'Filtro Y F-401 → boquilla atomizadora' },
      faseProducto: '🔵 Líquido presurizado',
    },
    torre: {
      id: 'torre', tipo: 'equipo', nombre: 'Torre de Secado por Atomización', etapa: 5,
      marca: 'GEA NIRO® Conventional Spray Dryer',
      pos: { x: 20, y: 37, w: 12, h: 14 }, alturaEq: 20, edificio: 'naveA',
      dims: 'Base 12 × 14 m · altura de cámara 15–20 m', peso: '80–120 t',
      alimentacion: '480 V, 3Ø, 60 Hz — Ventilador tiro inducido EF-101: 150 HP desde MCC-A (VFD-103)',
      consumos: 'Gas natural ~120 Nm³/h (aire caliente vía intercambiador con vapor S-1) · aire comprimido pulsos ciclones',
      materiales: 'Cámara AISI 316L · zona ATEX 20/21 interior',
      velocidad: '⛔ CUELLO DE BOTELLA: máx 1,500 kg/h de polvo',
      conexiones: { aguasArriba: 'P-101/P-102 (slurry a presión) · aire caliente del intercambiador (S-1)', aguasAbajo: 'Ciclones 1 y 2 → Enfriador VIBRO-FLUIDIZER · finos retornan por línea neumática' },
      faseProducto: '🟠 CAMBIO DE FASE: líquido → gránulo sólido · humedad <5 % · sale a 60–80 °C',
    },
    enfriador: {
      id: 'enfriador', tipo: 'equipo', nombre: 'Enfriador / Tamizador', etapa: 6,
      marca: 'GEA VIBRO-FLUIDIZER®',
      pos: { x: 34, y: 39, w: 4, h: 2 }, alturaEq: 1.8, edificio: 'naveA',
      dims: '~4 × 2 m · altura 1.8 m', peso: '3–5 t',
      alimentacion: '480 V, 3Ø, 60 Hz — 20–45 kW desde MCC-A',
      consumos: 'Aire filtrado de enfriamiento',
      materiales: 'AISI 316L · mallas clasificadoras',
      velocidad: '1,500 kg/h (acompaña a la torre)',
      conexiones: { aguasArriba: 'Torre GEA NIRO® (gránulo 60–80 °C)', aguasAbajo: 'Post-adición · finos → retorno neumático a torre' },
      faseProducto: '🟡 Gránulo <35 °C clasificado',
    },
    postadicion: {
      id: 'postadicion', tipo: 'equipo', nombre: 'Módulo de Post-Adición', etapa: 7,
      marca: 'Ribbon blender + dosificadores',
      pos: { x: 34, y: 44, w: 4, h: 2.5 }, alturaEq: 2.5, edificio: 'naveA',
      dims: '4 × 2.5 m', peso: '3 t',
      alimentacion: '480 V, 3Ø, 60 Hz — desde MCC-A',
      consumos: 'Dosificación de enzimas, fragancias y perlas',
      materiales: 'AISI 316L contacto con producto',
      velocidad: '1,500 kg/h',
      conexiones: { aguasArriba: 'Enfriador / tamizador', aguasAbajo: 'Tolvas buffer (tornillo helicoidal)' },
      faseProducto: '🟡 Polvo terminado',
    },
    tolvas: {
      id: 'tolvas', tipo: 'equipo', nombre: 'Tolvas Buffer (3 × 5,000 kg)', etapa: 8,
      marca: '3 tolvas de 5,000 kg c/u = 15,000 kg',
      pos: { x: 40, y: 41, w: 6, h: 3 }, alturaEq: 8, edificio: 'naveA',
      dims: '6.00 × 3.00 m · plataforma elevada', peso: '6 t vacías / 21 t llenas',
      alimentacion: '480 V, 3Ø — tornillos de descarga desde MCC-A',
      consumos: '—',
      materiales: 'Acero inoxidable · celdas de carga por tolva',
      velocidad: 'Autonomía a producción real: 15,000 / 1,125 = 13.3 h · la torre NUNCA se detiene (24/7)',
      conexiones: { aguasArriba: 'Post-adición (tornillo helicoidal)', aguasAbajo: 'Distribuidor de flujo → Módulo A (VFFS) o Módulo B (ensacadora)' },
      faseProducto: '🟡 Polvo almacenado',
    },
    distribuidor: {
      id: 'distribuidor', tipo: 'equipo', nombre: 'Distribuidor de Flujo (bifurcación)', etapa: 9,
      marca: 'Válvula desviadora de dos vías',
      pos: { x: 24, y: 63.5, w: 2, h: 1.5 }, alturaEq: 3, edificio: 'naveB',
      dims: '2 × 1.5 m', peso: '0.5 t',
      alimentacion: '480 V / neumática',
      consumos: 'Aire comprimido',
      materiales: 'AISI 316L',
      velocidad: 'Regla operativa: solo UN módulo (A o B) opera a la vez, NUNCA simultáneo',
      conexiones: { aguasArriba: 'Tolvas buffer (Nave A, por pasillo técnico)', aguasAbajo: 'Módulo A (VFFS) ó Módulo B (ensacadora)' },
      faseProducto: '🟡 Polvo',
    },
    vffs: {
      id: 'vffs', tipo: 'equipo', nombre: 'Envasadora VFFS — Módulo A (hogar)', etapa: 9,
      marca: 'ROVEMA BVC 600',
      pos: { x: 14, y: 67, w: 1.8, h: 1.2 }, alturaEq: 2.8, edificio: 'naveB',
      dims: '1.8 × 1.2 m · altura 2.8 m', peso: '<1.5 t',
      alimentacion: '480 V, 3Ø, 60 Hz — 75 HP asignados en MCC-B (VFD-201)',
      consumos: 'Aire comprimido 7 barg · film laminado',
      materiales: 'Contacto AISI 316L',
      velocidad: '500 g: 3,600 uds/h · 1 kg: 2,400 uds/h · 3 kg: 900 uds/h',
      conexiones: { aguasArriba: 'Distribuidor de flujo', aguasAbajo: 'Checkweigher + detector de metales → BC-101' },
      faseProducto: '🟢 Producto envasado (bolsas)',
    },
    ensacadora: {
      id: 'ensacadora', tipo: 'equipo', nombre: 'Ensacadora Automática — Módulo B (industrial)', etapa: 9,
      marca: 'HAVER & BOECKER INTEGRA® IV',
      pos: { x: 14, y: 72, w: 2.5, h: 2 }, alturaEq: 2.8, edificio: 'naveB',
      dims: '2.5 × 2.0 m · altura 2.8 m', peso: '2–3 t',
      alimentacion: '480 V, 3Ø, 60 Hz — 75 HP desde MCC-B (VFD-202)',
      consumos: 'Aire comprimido 7 barg · sacos de papel/PE',
      materiales: 'Contacto AISI 316L',
      velocidad: '5 kg: 540 uds/h · 20 kg: 180 uds/h · 50 kg: 90 uds/h',
      conexiones: { aguasArriba: 'Distribuidor de flujo', aguasAbajo: 'Checkweigher + detector de metales → BC-102' },
      faseProducto: '🟢 Producto envasado (sacos)',
    },
    checkweigher: {
      id: 'checkweigher', tipo: 'equipo', nombre: 'Checkweigher + Detector de Metales', etapa: 9,
      marca: 'Compartidos en línea (después del distribuidor)',
      pos: { x: 19.5, y: 69.7, w: 1.6, h: 1 }, alturaEq: 1.5, edificio: 'naveB',
      dims: '1.6 × 1.0 m', peso: '0.4 t',
      alimentacion: '120/208 V, 1Ø — desde TTD',
      consumos: '—',
      materiales: 'Acero inoxidable',
      velocidad: 'Acompaña al módulo activo · rechazo automático fuera de peso / con metal',
      conexiones: { aguasArriba: 'Módulo A o B', aguasAbajo: 'Bandas BC-101/BC-102 → paletizador' },
      faseProducto: '🟢 Producto envasado verificado',
    },
    bc101: {
      id: 'bc101', tipo: 'equipo', nombre: 'Banda Transportadora BC-101', etapa: 9,
      marca: 'Banda modular',
      pos: { x: 22, y: 68.5, w: 6, h: 0.8 }, alturaEq: 1, edificio: 'naveB',
      dims: '6.0 × 0.8 m', peso: '0.6 t',
      alimentacion: '480 V, 3Ø — 10 HP desde MCC-B (VFD-203)',
      consumos: '—', materiales: 'Banda PU grado alimentario',
      velocidad: 'Acompaña al módulo activo',
      conexiones: { aguasArriba: 'Checkweigher (línea Módulo A)', aguasAbajo: 'Paletizador robot' },
      faseProducto: '🟢 Bolsas sobre banda',
    },
    bc102: {
      id: 'bc102', tipo: 'equipo', nombre: 'Banda Transportadora BC-102', etapa: 9,
      marca: 'Banda modular reforzada',
      pos: { x: 22, y: 73.2, w: 6, h: 0.8 }, alturaEq: 1, edificio: 'naveB',
      dims: '6.0 × 0.8 m', peso: '0.7 t',
      alimentacion: '480 V, 3Ø — 10 HP desde MCC-B (VFD-204)',
      consumos: '—', materiales: 'Banda PU reforzada (sacos 50 kg)',
      velocidad: 'Acompaña al módulo activo',
      conexiones: { aguasArriba: 'Checkweigher (línea Módulo B)', aguasAbajo: 'Paletizador robot' },
      faseProducto: '🟢 Sacos sobre banda',
    },
    paletizador: {
      id: 'paletizador', tipo: 'equipo', nombre: 'Paletizador Robot', etapa: 10,
      marca: 'Brazo robótico antropomorfo',
      pos: { x: 30, y: 70.5, w: 2.2, h: 2.2 }, alturaEq: 3, edificio: 'naveB',
      dims: '2.2 × 2.2 m (celda con vallado)', peso: '2 t',
      alimentacion: '480 V, 3Ø, 60 Hz — 75 HP desde MCC-B',
      consumos: 'Aire comprimido (garra de vacío)',
      materiales: 'Celda con vallado de seguridad y escáner láser',
      velocidad: 'Patrones de mosaico por formato · pallets 1.20 × 1.00 m',
      conexiones: { aguasArriba: 'BC-101 / BC-102', aguasAbajo: 'Almacén temporal de pallets → 4 bahías de despacho (sur)' },
      faseProducto: '🟢 Pallets de producto terminado',
    },
  },

  // ---------------- FLUJO DE PROCESO (10 SUBPROCESOS) ----------------
  flujo: [
    { n: 1,  nombre: 'Recepción MP (silos exteriores)',        fase: 'Sólido/líquido a granel',                      color: '#8d6e63', equipo: 'silos',       temp: 'Ambiente' },
    { n: 2,  nombre: 'Dosificación y pesado (neumático)',      fase: 'Sólido en polvo',                              color: '#8d6e63', equipo: 'silos',       temp: 'Ambiente' },
    { n: 3,  nombre: 'Mezclado fase húmeda TK-101/TK-102',     fase: 'SLURRY LÍQUIDO 35–45 % sólidos',               color: '#2196f3', equipo: 'tk101',       temp: '65–75 °C' },
    { n: 4,  nombre: 'Bombeo y filtrado P-101/P-102',          fase: 'Líquido presurizado 100–250 bar',              color: '#2196f3', equipo: 'p101',        temp: '65–75 °C' },
    { n: 5,  nombre: 'Torre GEA NIRO® (CUELLO DE BOTELLA)',    fase: 'Líquido → gránulo sólido · humedad <5 %',      color: '#ff9800', equipo: 'torre',       temp: 'Sale a 60–80 °C' },
    { n: 6,  nombre: 'Enfriador/Tamizador VIBRO-FLUIDIZER',    fase: 'Gránulo <35 °C clasificado',                   color: '#fbc02d', equipo: 'enfriador',   temp: '<35 °C' },
    { n: 7,  nombre: 'Post-adición (enzimas, fragancias)',     fase: 'Polvo terminado',                              color: '#fbc02d', equipo: 'postadicion', temp: 'Ambiente' },
    { n: 8,  nombre: 'Tolvas buffer (tornillo helicoidal)',    fase: 'Polvo almacenado',                             color: '#fbc02d', equipo: 'tolvas',      temp: 'Ambiente' },
    { n: 9,  nombre: 'Envasado (Módulo A ó B) + CW + DM',      fase: 'Producto envasado',                            color: '#4caf50', equipo: 'vffs',        temp: 'Ambiente' },
    { n: 10, nombre: 'Paletizado robot → despacho (4 bahías)', fase: 'Pallets',                                      color: '#4caf50', equipo: 'paletizador', temp: 'Ambiente' },
  ],

  // ---------------- CAPACIDADES (ASIGNACIÓN #4) ----------------
  capacidades: {
    diseno:  { pct: 100, kgH: 1500, kgDia: 36000, kgMes: 1080000 },
    sistema: { pct: 85,  kgH: 1275, kgDia: 30600, kgMes: 918000 },
    real:    { pct: 75,  kgH: 1125, kgDia: 27000, kgMes: 810000 },
  },
  torreMaxKgH: 1500,
  tolvasCapacidadKg: 15000,

  formatos: {
    '500g': { nombre: 'Bolsa 500 g', udsH: 3600, kgUd: 0.5, modulo: 'A' },
    '1kg':  { nombre: 'Bolsa 1 kg',  udsH: 2400, kgUd: 1,   modulo: 'A' },
    '3kg':  { nombre: 'Bolsa 3 kg',  udsH: 900,  kgUd: 3,   modulo: 'A' },
    '5kg':  { nombre: 'Saco 5 kg',   udsH: 540,  kgUd: 5,   modulo: 'B' },
    '20kg': { nombre: 'Saco 20 kg',  udsH: 180,  kgUd: 20,  modulo: 'B' },
    '50kg': { nombre: 'Saco 50 kg',  udsH: 90,   kgUd: 50,  modulo: 'B' },
  },

  // Calendario semanal — 21 turnos (T1 06:00–14:00, T2 14:00–22:00, T3 22:00–06:00)
  // act: 'pack' | 'setup' (1 h de cambio + resto envasando formato destino) | 'mant' | 'libre'
  calendario: [
    { dia: 'Lunes',     turnos: [{ act: 'pack', formato: '500g' }, { act: 'pack', formato: '500g' }, { act: 'setup', de: '500g', a: '1kg' }] },
    { dia: 'Martes',    turnos: [{ act: 'pack', formato: '1kg' },  { act: 'pack', formato: '1kg' },  { act: 'pack', formato: '1kg' }] },
    { dia: 'Miércoles', turnos: [{ act: 'mant' }, { act: 'mant' }, { act: 'mant' }] },
    { dia: 'Jueves',    turnos: [{ act: 'setup', de: '1kg', a: '3kg' }, { act: 'pack', formato: '3kg' }, { act: 'pack', formato: '3kg' }] },
    { dia: 'Viernes',   turnos: [{ act: 'setup', de: '3kg', a: '5kg' }, { act: 'pack', formato: '5kg' }, { act: 'setup', de: '5kg', a: '20kg' }] },
    { dia: 'Sábado',    turnos: [{ act: 'pack', formato: '20kg' }, { act: 'setup', de: '20kg', a: '50kg' }, { act: 'pack', formato: '50kg' }] },
    { dia: 'Domingo',   turnos: [{ act: 'libre' }, { act: 'libre' }, { act: 'libre' }] },
  ],

  // ---------------- DATOS ELÉCTRICOS (ELEC-REF-001) ----------------
  electrico: {
    coordinacion: {
      main:   { nombre: 'Main Breaker Edif. C', amp: '1600 A', kaic: '65 kAIC', ei: '5.8 cal/cm²', frontRestr: '1.52 m', frontLim: '3.0 m' },
      ats:    { nombre: 'ATS 1600 A, 3P',       amp: '1600 A', kaic: '85 kAIC', ei: '4.1 cal/cm²', frontRestr: '1.37 m', frontLim: '2.5 m' },
      mccA:   { nombre: 'MCC-A Nave A',          amp: '1600 A', kaic: '65 kAIC', ei: '3.2 cal/cm²', frontRestr: '1.22 m', frontLim: '2.0 m' },
      mccB:   { nombre: 'MCC-B Nave B',          amp: '600 A nom / 800 A frame', kaic: '35 kAIC', ei: '2.0 cal/cm²', frontRestr: '1.07 m', frontLim: '1.5 m' },
      brkEns: { nombre: 'Breaker local ensacadora Mod. B', amp: '75 A (motor 75 HP)', kaic: '18 kAIC', ei: '<1.2 cal/cm²', frontRestr: '—', frontLim: '—' },
    },
    ieee519: {
      naveA: { thdvAntes: '18.7 %', thdvDespues: '3.2 %' },
      naveB: { thdvAntes: '15.3 %', thdvDespues: '2.9 %' },
      fpAntes: '0.82', fpDespues: '0.96',
    },
    epp: 'EPP Categoría 2 (ATPV 8.0 cal/cm²)',
  },
};

// Acceso unificado a la ficha de cualquier elemento clicable
function getItem(id) {
  return PLANT_DATA.equipos[id] || PLANT_DATA.edificios[id] || null;
}
